apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: sj47028zf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sj47028zf-python 
  name: sj47028zf-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sj47028zf-python
    weight: 100 
