apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sj47028zf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sj47028zf-python 
  name: sj47028zf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sj47028zf-python 
